[manager]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "none"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
cache_dir = ""

[opener]
edit = [
    { run = 'nvim "$@"', desc = "Edit in Neovim", block = true, for = "unix" },
]
open = [
    { run = 'open "$@"', desc = "Open", for = "macos" },
    { run = 'xdg-open "$@"', desc = "Open", for = "linux" },
]

[open]
rules = [
    { name = "*/", use = [ "edit", "open" ] },
]

[plugin]
prepend_previewers = [
    { name = "*.md", run = "glow" },
    { name = "*.json", run = "jq" },
]